name: Koogle API Build & Deploy
on:
  pull_request: 
    types:
      - closed
    branches:
      - main

jobs:
  build_deploy:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    name: Build and push
    environment: develop
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.sha }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - id: step1
        run: |
          echo "sha=$(echo $GITHUB_SHA)" >> $GITHUB_SHA

      - name: Build container image
        run: |
          docker build -t registry.digitalocean.com/sirgil-blockchain-registry/koogle-server:$(echo "$GITHUB_SHA" | head -c7) ./
       
        # uses: docker/build-push-action@v1
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_PASSWORD }}
        #   repository: 'TODO: figure it out'

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_KEY }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: |
          docker push registry.digitalocean.com/sirgil-blockchain-registry/koogle-server:$(echo "$GITHUB_SHA" | head -c7) 